### ISSUE TITLE
Compatible with Samsung Galaxy S7

### ISSUE THREAD

**Issue by numeralnathan** [lkorth/dislock#6]
I went to Google Play Store but I can't install this app on my Samsung Galaxy S7.  Google Play Store says that the app is incompatible with my phone.  Can you make the app compatible?

**Comment by lkorth** [comment]
No, in API 21 removing the pin or password no longer updates the lock screen to swipe to unlock or none until you reboot.

https://lukekorth.com/blog/android-5-breaks-dislock/
